// flow-typed signature: da9a69969ac9bc37f8c1777ef6dd0b5e
// flow-typed version: <<STUB>>/@types/react_v^16.8.22/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
